# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64" # 18.04
  # VM specifications
  config.vm.provider :virtualbox do |v|
      v.cpus = 4
      v.memory = 4096
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y git \
    wget
    snap install lxd --channel=3.0/stable
  SHELL
end
