# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64" # 18.04
  # VM specifications
  config.vm.provider :virtualbox do |v|
      v.cpus = 4
      v.memory = 4096
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y git \
    wget \
    nano \
    lxc
    cat /vagrant/lxc.init.yml | lxd init --preseed
    mkdir -p /home/vagrant/.config/lxc
    cp /etc/lxc/default.conf /home/vagrant/.config/lxc/default.conf
    echo "lxc.idmap = u 0 $(cat /etc/subuid | grep vagrant | cut -d ':' -f2) 65536" >> /home/vagrant/.config/lxc/default.conf
    echo "lxc.idmap = g 0 $(cat /etc/subuid | grep vagrant | cut -d ':' -f2) 65536" >> /home/vagrant/.config/lxc/default.conf
    echo "vagrant veth lxcbr0 10" >> /etc/lxc/lxc-usernet
  SHELL
end
# $ lxc --version
# 3.0.3
# centos	7	amd64	default	20190904_07:08
